backend:
  name: github
  repo: webgae/astro-decap-cms-blog
  branch: main
  base_url: https://astro-decap-cms-blog.vercel.app
  auth_endpoint: api/auth
  client_id: Ov23liCklzov2dSy8xKr

media_library:
  name: cloudinary
  config:
    cloud_name: djjiagkho
    api_key: 488363368914933
    upload_preset: decap-cms-unsigned

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Updated Date", name: "updatedDate", widget: "datetime", required: false}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
